export const siteConfig = {
    name: "Evaluator ANEVAR - Evaluator autorizat ANEVAR",
    description: "Servicii profesionale de evaluare imobiliară și evaluare capital pentru persoane fizice și juridice în Târgu Mureș și județul Mureș",
    keywords: [
        "evaluator",
        "ANEVAR",
        "evaluator autorizat",
        "evaluare imobiliare",
        "evaluare apartamente",
        "evaluare garsoniere",
        "evaluare terenuri",
        "evaluare case",
        "evaluare vile",
        "evaluare cabane",
        "evaluare spații comerciale",
        "evaluare spații industriale",
        "evaluare bunuri mobile",
        "evaluare autovehicule",
        "evaluare echipamente",
        "evaluare stocuri",
        "evaluare capital",
        "evaluare pentru garantarea împrumutului",
        "evaluare pentru informare",
        "evaluare pentru contabilitate",
        "evaluare pentru impozitare",
        "consultanță evaluare",
        "estimare valoare proprietate",
        "Târgu Mureș",
        "Mureș",
        "evaluator Târgu Mureș",
        "evaluator Mureș",
        "servicii evaluare imobiliare",
        "servicii evaluare bunuri",
        "raport evaluare",
        "preț evaluare",
        "evaluare profesionist",
        "site evaluări imobiliare"
    ]
}